version: 2.1

jobs:
  check_versions:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run: 
          name: Compare version
          command: |
            file_ver=$(cat version.json | jq -r '.version')
            git_tag=$(git describe --tags --abbrev=0)
            echo "Version defined in file: $file_ver"
            echo "Latest git tag: $git_tag"
            if [[ "$(printf '%s\n' "$file_ver" "$git_tag" | sort -V | tail -n1)" == "$git_tag" ]]; then 
              echo "release=no" >> $BASH_ENV
            else
              echo "release=yes" >> $BASH_ENV
            fi
            cp $BASH_ENV bash.env
            cat bash.env
      - persist_to_workspace:
          root: .
          paths:
            - bash.env
  deploy:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: |
            cat bash.env >> $BASH_ENV
            printenv release
      # - run: |
      #     printenv tag_ver
      - run:
          name: "Relese"
          command: "echo Relesing"
    approval:
      docker:
          - image:  cimg/base:stable
      steps:
        - run: printf "A hold job to wait for a manual approval"


workflows:
  general:
    jobs:
      - check_versions
      - approval:
          type: approval
      - deploy:
          requires:
          - hold

