version: 2.1

parameters:
  release:
    type: string
    default: "v0.0.2"

jobs:
  define_variables:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run: 
          name: Compare version
          command: |
            if [ "$(cat version.json | jq -r '.version')" > "$(git describe --tags --abbrev=0)" ]; then 
              echo release=yes >> "$BASH_ENV";
            else 
              release=no >> "$BASH_ENV"; 
            fi
            cp $BASH_ENV bash.env
            cat bash.env
      # - persist_to_workspace:
      #     root: .
      #     paths:
      #       - bash.env
  deploy:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      # - attach_workspace:
      #     at: .
      # - run: |
      #     cat bash.env >> $BASH_ENV
      # - run: |
      #     printenv tag_ver
      - run:
          name: "Relese"
          command: "echo Relesing"


workflows:
  general:
    jobs:
      - define_variables
      - deploy:
          requires:
          - define_variables



# #             # echo file_ver=$(cat version.json | jq -r '.version') >> "$BASH_ENV"
#             # echo git_tag=$(git describe --tags --abbrev=0) >> "$BASH_ENV"
#                         echo $release
#             cp $BASH_ENV bash.env
#             cat bash.env