version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "ls -la"
  say-godbye:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say goodbye"
          command: "ls -la"
  define_condition_job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: 
          name: check
          command: |
            ver=$(cat version.json | jq '.version')
            echo $ver
      - parameters:
          release:
            type: string
            default: "echo ${ver}"

workflows:
  define_update_condition:
    jobs:
      - define_condition_job

  # first-wf:
  #   when: 
  #     equal: [ "v0.0.2", << pipeline.parameters.release >> ]
  #   jobs:
  #     - say-hello
  #     - say-godbye:
  #         requires:
          # - say-hello
