version: 2.1

executors:
  node:
    docker:
      - image: cimg/base:stable   

jobs:
  check_versions:
    executor: node
    resource_class: small
    steps:
      - checkout
      - run: 
          name: Compare version
          command: |
            file_ver=$(cat version.json | jq -r '.version')
            git_tag=$(git describe --tags --abbrev=0)
            if [[ "$(printf '%s\n' "$file_ver" "$git_tag" | sort -V | tail -n1)" == "$git_tag" ]]; then 
              release=false
            else
              release=true
            fi
            echo "Version defined in file: $file_ver"
            echo "Latest git tag: $git_tag"
            echo "Release: $release"
  deploy:
    executor: node
    resource_class: small
    steps:
      - checkout
    
workflows:
  general:
    jobs:
      - check_versions
      - deploy:
          requires:
           - check_versions


