version: 2.1

executors:
  node:
    docker:
      - image: cimg/base:stable   

jobs:
  check_versions:
    executor: node
    resource_class: small
    steps:
      - checkout
      - run: 
          name: Compare version
          command: |
            file_ver=$(cat version.json | jq -r '.version')
            git_tag=$(git describe --tags --abbrev=0)
            if [[ "$(printf '%s\n' "$file_ver" "$git_tag" | sort -V | tail -n1)" == "$git_tag" ]]; then 
              release=false
            else
              release=true
            fi
            echo "Version defined in file: $file_ver"
            echo "Latest git tag: $git_tag"
            echo "release=$release" >> $BASH_ENV
            cp $BASH_ENV bash.env
      - persist_to_workspace:
          root: .
          paths:
            - bash.env
  deploy:
    executor: node
    resource_class: small
    steps:
      - attach_workspace:
          at: .
      - run: |
          cat bash.env >> $BASH_ENV
          cat $BASH_ENV
      - when:
          condition:
            matches:
              pattern: 'true'
              value: $release
          steps:
            - checkout
    
workflows:
  general:
    jobs:
      - check_versions
      - deploy:
          requires:
           - check_versions


