version: 2.1

parameters:
  release:
    type: string
    default: "v0.0.2"

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      # - attach_workspace:
      #     at: .
      # - run: |
      #     cat bash.env >> $BASH_ENV
      # - run: |
      #     printenv tag_ver
      - run:
          name: "Say hello"
          command: "ls -la"
  define_variables:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run: 
          name: Set versions
          command: |
            ver=$(cat version.json | jq '.version')
            tag_ver=$(git describe --tags --abbrev=0)
            echo file_ver=$ver >> "$BASH_ENV"
            echo git_tag=$tag_ver >> "$BASH_ENV"
            echo $BASH_ENV
            cp $BASH_ENV bash.env
            cat bash.env
      - persist_to_workspace:
          root: .
          paths:
            - bash.env

workflows:
  general:
    jobs:
      - define_variables
      - say-hello:
          requires:
          - define_variables
